server:
  port: 8088
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: utf-8
spring:
  data:
    mongodb:
      host: 114.116.22.152
      port: 27017
      database: campus
      username: xt
      password: 2069562412xt
      authentication-database: admin